# Generated by Django 3.2.8 on 2021-10-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=11)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('necessity', models.CharField(choices=[('R', 'Roupa'), ('A', 'Alimento'), ('D', 'Dinheiro')], max_length=1)),
            ],
        ),
    ]
